### ISSUE TITLE
Esempi di utilizzo

### ISSUE THREAD

**Issue by alessandromagridotnet** [devcode-it/cbi#2]
Buongiorno,
anzitutto grazie per la libreria!
Sarebbe interessante ci fosse una maggiore documentazione con degli esempi completi, sia per quanto riguarda la generazione delle riba, sia per la loro lettura.

**Comment by Dasc3er** [comment]
Ciao @alessandromagridotnet , grazie per l'interessamento!
Ho appena aggiunto un test rapido per la generazione con alcuni dati fittizi: https://github.com/devcode-it/cbi/commit/79bfc84ebefab37d56174138f1903235514d47b4
Per quanto riguarda la lettura, al momento sono stati effettuati dei test basilari e non esistono delle classi di supporto (come `Intestazione` e `Ricevuta` per la generazione): la lettura richiede di lavorare riga per riga del file, leggendo in particolare i primi due caratteri `<tipo>` e utilizzando la relativa classe `Record<tipo>`.

Se sei interessato a migliorare il codice e la documentazione, oppure anche solo a fornire suggerimenti, sei il benvenuto!

**Comment by alessandromagridotnet** [comment]
Ora è molto più chiaro.
Grazie mille!
